name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyBCR9HnlSOWx4h-qg-L6_StN4t3OSbbMA8
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: charith-c014a.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: charith-c014a
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: charith-c014a.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 471604447420
          NEXT_PUBLIC_FIREBASE_APP_ID: 1:471604447420:web:41697e65cec06ddfab28b9
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-08Q08R6R3S

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHARITH_C014A }}
          channelId: live
          projectId: charith-c014a
